#pragma once

char elem_fmt_start[] =
"    <Paragraph Type=\"%s\" Alignment=\"%s\">\n"
"      <Text>";

char elem_fmt_end[] ="</Text>\n"
"    </Paragraph>\n";

char default_characters[] =
"    <Characters />\n";

char default_extensions[] =
"    <Extensions>\n"
"      <Extension>(V.O.)</Extension>\n"
"      <Extension>(O.S.)</Extension>\n"
"      <Extension>(O.C.)</Extension>\n"
"      <Extension>(CONT'D)</Extension>\n"
"      <Extension>(SUBTITLE)</Extension>\n"
"    </Extensions>\n";

char default_scene_intros[] =
"    <SceneIntros Separator=\". \">\n"
"      <SceneIntro>INT</SceneIntro>\n"
"      <SceneIntro>EXT</SceneIntro>\n"
"      <SceneIntro>I/E</SceneIntro>\n"
"    </SceneIntros>\n";

char default_locations[] =
"    <Locations />\n";

char default_times_of_day[] =
"    <TimesOfDay Separator=\" - \">\n"
"      <TimeOfDay>DAY</TimeOfDay>\n"
"      <TimeOfDay>NIGHT</TimeOfDay>\n"
"      <TimeOfDay>AFTERNOON</TimeOfDay>\n"
"      <TimeOfDay>MORNING</TimeOfDay>\n"
"      <TimeOfDay>EVENING</TimeOfDay>\n"
"      <TimeOfDay>LATER</TimeOfDay>\n"
"      <TimeOfDay>MOMENTS LATER</TimeOfDay>\n"
"      <TimeOfDay>CONTINUOUS</TimeOfDay>\n"
"      <TimeOfDay>THE NEXT DAY</TimeOfDay>\n"
"      <TimeOfDay>MAGIC HOUR</TimeOfDay>\n"
"      <TimeOfDay>DAWN</TimeOfDay>\n"
"      <TimeOfDay>DUSK</TimeOfDay>\n"
"      <TimeOfDay>SAME</TimeOfDay>\n"
"      <TimeOfDay>SAME TIME</TimeOfDay>\n"
"    </TimesOfDay>\n";

char default_transitions[] =
"    <Transitions>\n"
"      <Transition>CUT TO:</Transition>\n"
"      <Transition>FADE IN:</Transition>\n"
"      <Transition>FADE OUT.</Transition>\n"
"      <Transition>FADE TO:</Transition>\n"
"      <Transition>DISSOLVE TO:</Transition>\n"
"      <Transition>BACK TO:</Transition>\n"
"      <Transition>MATCH CUT TO:</Transition>\n"
"      <Transition>JUMP CUT TO:</Transition>\n"
"      <Transition>FADE TO BLACK.</Transition>\n"
"      <Transition>SMASH CUT TO:</Transition>\n"
"      <Transition>CUT TO BLACK.</Transition>\n"
"      <Transition>TIME CUT:</Transition>\n"
"    </Transitions>\n";

char file_fmt[] =
"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\" ?>\n"
"<FinalDraft DocumentType=\"Script\" Template=\"No\" Version=\"4\">\n"
"\n"
"  <Content>\n%s</Content>\n"
"\n"
"  <ElementSettings Type=\"General\">\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"\"/>\n"
"    <ParagraphSpec Alignment=\"Left\" FirstIndent=\"0.00\" Leading=\"Regular\" LeftIndent=\"1.50\" RightIndent=\"7.50\" SpaceBefore=\"0\" Spacing=\"1\" StartsNewPage=\"No\"/>\n"
"    <Behavior PaginateAs=\"General\" ReturnKey=\"General\" Shortcut=\"0\"/>\n"
"  </ElementSettings>\n"
"\n"
"  <ElementSettings Type=\"Scene Heading\">\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"AllCaps\"/>\n"
"    <ParagraphSpec Alignment=\"Left\" FirstIndent=\"0.00\" Leading=\"Regular\" LeftIndent=\"1.50\" RightIndent=\"7.50\" SpaceBefore=\"24\" Spacing=\"1\" StartsNewPage=\"No\"/>\n"
"    <Behavior PaginateAs=\"Scene Heading\" ReturnKey=\"Action\" Shortcut=\"1\"/>\n"
"  </ElementSettings>\n"
"\n"
"  <ElementSettings Type=\"Action\">\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"\"/>\n"
"    <ParagraphSpec Alignment=\"Left\" FirstIndent=\"0.00\" Leading=\"Regular\" LeftIndent=\"1.50\" RightIndent=\"7.50\" SpaceBefore=\"12\" Spacing=\"1\" StartsNewPage=\"No\"/>\n"
"    <Behavior PaginateAs=\"Action\" ReturnKey=\"Action\" Shortcut=\"2\"/>\n"
"  </ElementSettings>\n"
"\n"
"  <ElementSettings Type=\"Character\">\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"AllCaps\"/>\n"
"    <ParagraphSpec Alignment=\"Left\" FirstIndent=\"0.00\" Leading=\"Regular\" LeftIndent=\"3.50\" RightIndent=\"7.25\" SpaceBefore=\"12\" Spacing=\"1\" StartsNewPage=\"No\"/>\n"
"    <Behavior PaginateAs=\"Character\" ReturnKey=\"Dialogue\" Shortcut=\"3\"/>\n"
"  </ElementSettings>\n"
"\n"
"  <ElementSettings Type=\"Parenthetical\">\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"\"/>\n"
"    <ParagraphSpec Alignment=\"Left\" FirstIndent=\"-0.10\" Leading=\"Regular\" LeftIndent=\"3.00\" RightIndent=\"5.50\" SpaceBefore=\"0\" Spacing=\"1\" StartsNewPage=\"No\"/>\n"
"    <Behavior PaginateAs=\"Parenthetical\" ReturnKey=\"Dialogue\" Shortcut=\"4\"/>\n"
"  </ElementSettings>\n"
"\n"
"  <ElementSettings Type=\"Dialogue\">\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"\"/>\n"
"    <ParagraphSpec Alignment=\"Left\" FirstIndent=\"0.00\" Leading=\"Regular\" LeftIndent=\"2.50\" RightIndent=\"6.00\" SpaceBefore=\"0\" Spacing=\"1\" StartsNewPage=\"No\"/>\n"
"    <Behavior PaginateAs=\"Dialogue\" ReturnKey=\"Action\" Shortcut=\"5\"/>\n"
"  </ElementSettings>\n"
"\n"
"  <ElementSettings Type=\"Transition\">\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"AllCaps\"/>\n"
"    <ParagraphSpec Alignment=\"Right\" FirstIndent=\"0.00\" Leading=\"Regular\" LeftIndent=\"5.50\" RightIndent=\"7.10\" SpaceBefore=\"12\" Spacing=\"1\" StartsNewPage=\"No\"/>\n"
"    <Behavior PaginateAs=\"Transition\" ReturnKey=\"Scene Heading\" Shortcut=\"6\"/>\n"
"  </ElementSettings>\n"
"\n"
"  <ElementSettings Type=\"Shot\">\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"AllCaps\"/>\n"
"    <ParagraphSpec Alignment=\"Left\" FirstIndent=\"0.00\" Leading=\"Regular\" LeftIndent=\"1.50\" RightIndent=\"7.50\" SpaceBefore=\"24\" Spacing=\"1\" StartsNewPage=\"No\"/>\n"
"    <Behavior PaginateAs=\"Scene Heading\" ReturnKey=\"Action\" Shortcut=\"7\"/>\n"
"  </ElementSettings>\n"
"\n"
"  <ElementSettings Type=\"Cast List\">\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"AllCaps\"/>\n"
"    <ParagraphSpec Alignment=\"Left\" FirstIndent=\"0.00\" Leading=\"Regular\" LeftIndent=\"1.50\" RightIndent=\"7.50\" SpaceBefore=\"0\" Spacing=\"1\" StartsNewPage=\"No\"/>\n"
"    <Behavior PaginateAs=\"Action\" ReturnKey=\"Action\" Shortcut=\"8\"/>\n"
"  </ElementSettings>\n"
"\n"
"  <ElementSettings Type=\"New Act\">\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"Bold+Underline+AllCaps\"/>\n"
"    <ParagraphSpec Alignment=\"Center\" FirstIndent=\"0.00\" Leading=\"Regular\" LeftIndent=\"1.50\" RightIndent=\"7.50\" SpaceBefore=\"12\" Spacing=\"1\" StartsNewPage=\"Yes\"/>\n"
"    <Behavior PaginateAs=\"Scene Heading\" ReturnKey=\"Scene Heading\" Shortcut=\"9\"/>\n"
"  </ElementSettings>\n"
"\n"
"  <ElementSettings Type=\"End of Act\">\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"Bold+Underline+AllCaps\"/>\n"
"    <ParagraphSpec Alignment=\"Center\" FirstIndent=\"0.00\" Leading=\"Regular\" LeftIndent=\"1.50\" RightIndent=\"7.50\" SpaceBefore=\"24\" Spacing=\"1\" StartsNewPage=\"No\"/>\n"
"    <Behavior PaginateAs=\"Character\" ReturnKey=\"New Act\" Shortcut=\":\"/>\n"
"  </ElementSettings>\n"
"\n"
"  <TitlePage>\n"
"    <Content>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph Alignment='Center'>\n"
"        <Text>Kya Karna Hai?</Text>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph Alignment='Center'>\n"
"        <Text>by</Text>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph>\n"
"        <Text/>\n"
"      </Paragraph>\n"
"      <Paragraph Alignment='Center'>\n"
"        <Text>Hritik Dutta, Nilay Pant</Text>\n"
"      </Paragraph>\n"
"    </Content>\n"
"  </TitlePage>\n"
"\n"
"  <UnanchoredScriptNotes/>\n"
"\n"
"  <SmartType>\n%s%s%s%s%s%s</SmartType>\n"
"\n"
"  <MoresAndContinueds>\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"\"/>\n"
"    <DialogueBreaks AutomaticCharacterContinueds=\"Yes\" BottomOfPage=\"Yes\" DialogueBottom=\"(MORE)\" DialogueTop=\"(CONT'D)\" TopOfNext=\"Yes\"/>\n"
"    <SceneBreaks ContinuedNumber=\"No\" SceneBottom=\"(CONTINUED)\" SceneBottomOfPage=\"No\" SceneTop=\"CONTINUED:\" SceneTopOfNext=\"No\"/>\n"
"  </MoresAndContinueds>\n"
"\n"
"  <LockedPages/>\n"
"\n"
"  <Macros>\n"
"    <Macro Element=\"Scene Heading\" Name=\"INT\" Shortcut=\"Ctrl+Alt+1\" Text=\"INT. \" Transition=\"None\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Scene Heading\" Name=\"EXT\" Shortcut=\"Ctrl+Alt+2\" Text=\"EXT. \" Transition=\"None\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Scene Heading\" Name=\"I/E\" Shortcut=\"Ctrl+Alt+3\" Text=\"I/E \" Transition=\"None\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Scene Heading\" Name=\"DAY\" Shortcut=\"Ctrl+Alt+4\" Text=\" - DAY\" Transition=\"Action\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Scene Heading\" Name=\"NIGHT\" Shortcut=\"Ctrl+Alt+5\" Text=\" - NIGHT\" Transition=\"Action\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Scene Heading\" Name=\"SUNRISE\" Shortcut=\"Ctrl+Alt+6\" Text=\" - SUNRISE\" Transition=\"Action\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Scene Heading\" Name=\"MAGIC\" Shortcut=\"Ctrl+Alt+7\" Text=\" - MAGIC\" Transition=\"Action\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Parenthetical\" Name=\"CONT\" Shortcut=\"Ctrl+Alt+8\" Text=\"continuing\" Transition=\"Dialogue\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Parenthetical\" Name=\"INTER\" Shortcut=\"Ctrl+Alt+9\" Text=\"interrupting\" Transition=\"Dialogue\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"None\" Name=\"\" Shortcut=\"Ctrl+Alt+0\" Text=\"\" Transition=\"None\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Transition\" Name=\"CUTTO\" Shortcut=\"Ctrl+Shift+Alt+1\" Text=\"CUT TO:\" Transition=\"Scene Heading\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Action\" Name=\"FADEIN\" Shortcut=\"Ctrl+Shift+Alt+2\" Text=\"FADE IN:\" Transition=\"Scene Heading\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Transition\" Name=\"FADEOUT\" Shortcut=\"Ctrl+Shift+Alt+3\" Text=\"FADE OUT.\" Transition=\"Scene Heading\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Transition\" Name=\"FADETO\" Shortcut=\"Ctrl+Shift+Alt+4\" Text=\"FADE TO:\" Transition=\"Scene Heading\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Transition\" Name=\"DISSLV\" Shortcut=\"Ctrl+Shift+Alt+5\" Text=\"DISSOLVE TO:\" Transition=\"Scene Heading\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Transition\" Name=\"BACKTO\" Shortcut=\"Ctrl+Shift+Alt+6\" Text=\"BACK TO:\" Transition=\"Scene Heading\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Transition\" Name=\"MATCHCUT\" Shortcut=\"Ctrl+Shift+Alt+7\" Text=\"MATCH CUT TO:\" Transition=\"Scene Heading\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Transition\" Name=\"JUMPCUT\" Shortcut=\"Ctrl+Shift+Alt+8\" Text=\"JUMP CUT TO:\" Transition=\"Scene Heading\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"Transition\" Name=\"FBLACK\" Shortcut=\"Ctrl+Shift+Alt+9\" Text=\"FADE TO BLACK.\" Transition=\"None\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"    <Macro Element=\"None\" Name=\"\" Shortcut=\"E\" Text=\"\" Transition=\"None\">\n"
"      <Alias Confirm=\"No\" MatchCase=\"No\" SmartReplace=\"Yes\" Text=\"\" WordOnly=\"No\">\n"
"        <ActivateIn Element=\"General\"/>\n"
"        <ActivateIn Element=\"Scene Heading\"/>\n"
"        <ActivateIn Element=\"Action\"/>\n"
"        <ActivateIn Element=\"Character\"/>\n"
"        <ActivateIn Element=\"Parenthetical\"/>\n"
"        <ActivateIn Element=\"Dialogue\"/>\n"
"        <ActivateIn Element=\"Transition\"/>\n"
"        <ActivateIn Element=\"Shot\"/>\n"
"      </Alias>\n"
"    </Macro>\n"
"  </Macros>\n"
"\n"
"  <SceneNumberOptions LeftLocation=\"0.75\" NumberScheme=\"1A\" RightLocation=\"7.38\" ShowNumbersOnLeft=\"Yes\" ShowNumbersOnRight=\"Yes\">\n"
"    <FontSpec AdornmentStyle=\"0\" Background=\"#FFFFFFFFFFFF\" Color=\"#000000000000\" Font=\"Courier Final Draft\" RevisionID=\"0\" Size=\"12\" Style=\"\"/>\n"
"  </SceneNumberOptions>\n"
"\n"
"  <Images Hidden=\"0\"/>\n"
"\n"
"</FinalDraft>\n";